spring:
  datasource:
    url: jdbc:mysql://localhost:3306/arquetipo
    username: root
    password: german28.
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
  application:
    name: orders-service
  profiles: qa

server:
  port: 8090

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${APIMANAGER_SVC_SERVICE_HOST}:${APIMANAGER_SVC_PORT_8000_TCP_PORT}/eureka
  instance:
    leaseRenewalIntervalInSeconds: 5   
    preferIpAddress: true
